# Generated by Django 4.1.3 on 2023-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_main_model',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_main_model',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_main_model',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
